export const DISPLAY_ALERT = "SHOW_ALERT"
export const CLEAR_ALERT = "CLEAR_ALERT"

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const ADD_USER_BEGIN = "ADD_USER_BEGIN";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

export const CLEAR_FILTERS = "CLEAR_FILTERS"

export const GET_ALL_USERS_BEGIN = "GET_ALL_USERS_BEGIN"
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS"

export const CHANGE_PAGE = "CHANGE_PAGE"

export const GET_ALL_TASKS_BEGIN = "GET_ALL_TASKS_BEGIN"
export const GET_ALL_TASKS_SUCCESS = "GET_ALL_TASKS_SUCCES"

export const ADD_TASK_BEGIN = "ADD_TASK_BEGIN";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_ERROR = "ADD_TASK_ERROR";

export const DELETE_TASK_BEGIN = "DELETE_TASK_BEGIN";

export const EDIT_TASK_BEGIN = "EDIT_TASK_BEGIN"

export const GET_TASK_BEGIN = "GET_TASK_BEGIN";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_ERROR = "GET_TASK_ERROR";

export const ADD_COMMENT_BEGIN = "ADD_COMMENT" ;
export const DELETE_COMMENT_BEGIN = "DELETE_COMMENT"
export const UPDATE_COMMENT_BEGIN = "UPDATE_COMMENT"


export const ADD_RECORD_BEGIN = "ADD_RECORD_BEGIN";
export const ADD_RECORD_SUCCESS = "ADD_RECORD_SUCCESS";
export const ADD_RECORD_ERROR = "ADD_RECORD_ERROR";